name = "chumo-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# [env.staging]
# vars = { ENVIRONMENT = "staging" }

# [env.production]
# vars = { ENVIRONMENT = "production" }
